### ISSUE TITLE
Chap04. 엔티티 매핑, Chap05. 연관관계 매핑 기초

### ISSUE THREAD

**Issue by sksk713** [sksk713/study#2]

**Comment by yejiin** [comment]
SEQUENCE 전략의 경우

em.persist()를 하게 되면 먼저 DB의 시퀀스를 조회해서 할당할 값을 불러온다.
영속 상태에 있는 엔티티에 해당 값을 할당한다.
와 같이 동작하게 되는데, https://github.com/entity로 선언한 클래스에 Setter가 없어도 놀랍게 동작합니다.. 그 이유는 뭘까요?? 기본 생성자밖에 없고 임의로 정의한 생성자도 없습니다...

**Comment by yejiin** [comment]
> SEQUENCE 전략의 경우
> 
> em.persist()를 하게 되면 먼저 DB의 시퀀스를 조회해서 할당할 값을 불러온다. 영속 상태에 있는 엔티티에 해당 값을 할당한다. 와 같이 동작하게 되는데, [https://github.com/entity로](https://github.com/entity%EB%A1%9C) 선언한 클래스에 Setter가 없어도 놀랍게 동작합니다.. 그 이유는 뭘까요?? 기본 생성자밖에 없고 임의로 정의한 생성자도 없습니다...

답변1
